### ISSUE TITLE
Set default sub account ID to 1.

### ISSUE THREAD

**Issue by MeanBoyCousin** [8ball030/hundred_x#2]
https://github.com/8ball030/hundred_x/blob/d58a7c682eac8e2facfc7fa495a345ecc8bb335b/hundred_x/client.py#L41

**Comment by 8ball030** [comment]
Dude this *should be 1 right?

**Comment by wakamex** [comment]
I've been using subaccount 0 because when I clicked deposit through the UI on a brand new address it seemed to show up in subaccount 0

**Comment by MeanBoyCousin** [comment]
Subaccount 0 is the default for the 100x UI. We are encouraging SDK and client builders to use 1 as the default to establish a standard. There is how ever nothing to stop anyone from using subaccount 0 and being able to then use the UI to view orders. Please just be aware that the UI may not be super responsive if you're running any form of high frequency strategy.
